### ISSUE TITLE
finetune on shapenetpart

### ISSUE THREAD

**Issue by yuyouxixi** [wangzy22/TAP#2]
Hello, thanks for your wonderful work!

It seems that the guidelines for pretraining and finetuning on segmentation task, i.e. shapenetpart are not given.  I followed the command 'python examples/classification/main.py --cfg cfgs/shapenet/pointmlp_pretrain.yaml' to get the pretrained weight. 

Since there is no guideline for shapenetpart,  I just used ' python examples/shapenetpart/main.py --cfg cfgs/shapenetpart/pointmlp_finetune.yaml' and got the following error. 

![image](https://github.com/wangzy22/TAP/assets/41193400/02e26195-af8c-4e96-b8a6-29d293abf891)

It seems that the segmentation model architecture is not the same as the pretrained model.  Could you help me solve this problem and give some guidelines for part segmentation task?

**Comment by yuyouxixi** [comment]
Also, I noticed that the in_channels of pretrained weight downloaded from cloud are different. The in_channel is 4 for classification task  and 3 for segmentation task.  However, the in_channel in the released code of segmentation task (in pointmlp_seg.py) is 6.

Why are they different? It seems that the segmentation pretrained weight download from the cloud cannot be directly used to finetune the model.

**Comment by wangzy22** [comment]
Hi, thanks for your interest in our work!

Actually, the loading weight operation in part segmentation takes place in this [function](https://github.com/wangzy22/TAP/blob/32598336ae80ffbeb246f20e1e54b35326c4a135/openpoints/models/segmentation/base_seg.py#L82C46-L82C46) in `openpoints/models/segmentation/base_seg.py`, not `load_checkpoint` function in `examples/shapenetpart/main.py`. Therefore, the correct modification of `cfgs/shapenetpart/pointmlp_finetune.yaml` is to replace variables `model.segmentor_args.pretrained_path` in this [line](https://github.com/wangzy22/TAP/blob/32598336ae80ffbeb246f20e1e54b35326c4a135/cfgs/shapenetpart/pointmlp_finetune.yaml#L5) with your pre-trained weight path. Please do not specify the global variable `pretrained_path` in part segmentation finetune config as classification configs, so that the `load_checkpoint` function won't be called.

As for the `in_channel` misalignment, this is due to the additional normal information used in ShapeNetPart part segmentation task. We follow [PointNeXt](https://github.com/guochengqian/PointNeXt) and common practice to use both point cloud coordinate (3 channels) and point cloud normal (3 channels) as the input of part segmentation task. However, during the pre-training procedure, for fair comparison, we assume that normal information is not available in ShapeNet pre-training dataset and we only use point cloud coordinate (3 channels) for pre-training. Classification codes use 4 channels input since they use an additional `height` channel, also following the setting in PointNeXt. You can refer to this [line](https://github.com/wangzy22/TAP/blob/32598336ae80ffbeb246f20e1e54b35326c4a135/openpoints/dataset/shapenet/shapenet55.py#L103) to see what these four channels are composed of. To deal with the input channel misalignment in part segmentation, we just omit loading `embedding.net.0.weight` in this [line](https://github.com/wangzy22/TAP/blob/32598336ae80ffbeb246f20e1e54b35326c4a135/openpoints/models/segmentation/base_seg.py#L89).

Hopefully these information would solve your concerns.

**Comment by yuyouxixi** [comment]
Thank you for your reply. That sloves my concerns.
