### ISSUE TITLE
How to use a pre-trained model to generate images at specific pose from custom point clouds

### ISSUE THREAD

**Issue by Zsy103** [wangzy22/TAP#5]
Hi,

Thank you for making such great work public! As shown in fig/tap.png, the input of the model is a point cloud and pose, and the output is a picture. I want to just use a pre-trained model to generate images at specific pose from custom point clouds, could you please provide an example?

Many thanks

**Comment by wangzy22** [comment]
Hi, thanks for your interest in our work!

Unfortunately, this model may not meet your requirement. Since our method is target at pre-training the point cloud backbone model to extract more representative features that can be adapted to downstream perception tasks, the generated images may not be satisfactory if given point cloud and pose is out-of-distribution. :(
